export const FETCH_ARTICLE_PENDING = 'FETCH_ARTICLE_PENDING';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR';

export const KEYWORD_UPDATE = 'KEYWORD_UPDATE';
